language: ruby
cache: bundler
sudo: false
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - ruby-head
  - jruby-9.2.11.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
