language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - jruby-9.2.0.0
before_install:
  - gem update --system
  - gem install bundler --no-document
after_success:
  - bundle exec codeclimate-test-reporter
